yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='homepage'),
    # Страница группы
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Новая запись
    path('create/', views.post_create, name='post_create'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/',
         views.post_edit, name='post_edit'
         ),
    # Добавление комментария
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    # Путь к админке сайта
    path('admin/', admin.site.urls),
    # Путь к модулю регистрации и аутентификации пользователя
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

SYMBOLS_AMOUNT = 15


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Ссылка на группу', unique=True)
    description = models.TextField('Описание группы')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        # Выводим текст поста
        return self.text[:SYMBOLS_AMOUNT]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемый пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': ('Текст поста'),
            'group': ('Группа'),
            'image': ('Картинка')
        }
        help_texts = {
            'text': ('Текст поста не может быть пустым')
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError(
                'Вы обязательно должны что-нибудь написать!'
            )
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': ('Текст комментария')
        }
        help_text = {
            'text': ('Текст комментария не может быть пустым')
        }

    def clean_comment_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError(
                'Вы обязательно должны что-нибудь написать!'
            )
        return data

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User

POSTS_AMOUNT = 10


def get_page_obj(queryset, request):
    """Создание Paginator с нужным queryset"""
    paginator = Paginator(queryset, POSTS_AMOUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20 * 15)
def index(request):
    """Главная страница"""
    context = {
        'page_obj': get_page_obj(Post.objects.all(), request)
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Получение постов нужной группы по запросу"""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'group': group,
        'page_obj': get_page_obj(posts, request)
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Отображение профиля пользователя"""
    # Код запроса к модели User
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    post_quantity = author.posts.count()
    following = (request.user.is_authenticated
                 and Follow.objects.filter(
                     user=request.user,
                     author=author).exists())
    context = {
        'username': author,
        'post_quantity': post_quantity,
        'page_obj': get_page_obj(post_list, request),
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Функция для просмотра поста и комментариев"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Функция создания нового поста"""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    user = request.user
    context = {
        'form': form
    }
    if not form.is_valid():
        return render(request, 'posts/post_create.html', context)
    new_post = form.save(commit=False)
    new_post.author = user
    new_post.save()
    return redirect('posts:profile', user.username)


@login_required
def post_edit(request, post_id):
    """Функция для редактирования поста"""
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': PostForm(instance=post),
        'post': post,
        'is_edit': True
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    '''Добавление комментария'''
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    '''Лента постов от авторов из подписок'''
    context = {
        'page_obj': get_page_obj(
            Post.objects.select_related(
                'author'
            ).filter(
                author__following__user=request.user
            ),
            request
        )
    }
    return render(request, 'posts/follow_index.html', context)


@login_required
def profile_follow(request, username):
    '''Подписаться на автора'''
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    '''Отписаться от автора'''
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow_index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Избранные авторы {% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <div class="container py-5">
      <h1> Избранные авторы </h1>
    {% for post in page_obj %}
    <article>  
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <p>
        <a href="{% url 'posts:post_detail' post.pk %}"> Подробная информация</a>
      </p>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи
          группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <p>
        <a href="{% url 'posts:post_detail' post.pk %}"> Подробная информация</a>
      </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>
{% include 'posts/includes/paginator.html' %}  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
{% load thumbnail %}
{% include 'posts/includes/switcher.html' %}
<div class="container py-5"> 
  <h1>Последние обновления на сайте</h1>
{% for post in page_obj %}
  <article>  
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <p>
      <a href="{% url 'posts:post_detail' post.pk %}"> Подробная информация</a>
    </p>
  {% if post.group %}   
    <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
  {% endif %}
  </article> 
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
</div>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактировать запись
{% else %}
Добавить запись
{% endif %}  
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">       
        {% if is_edit %}
          Сохранить запись
        {% else %}
          Добавить запись
        {% endif %}              
      </div>
      <div class="card-body">

        {% if is_edit %}
          <form method="post" action="{% url 'posts:post_edit' post.pk %}" enctype="multipart/form-data">
        {% else %}
          <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
        {% endif %}              
        
        {% csrf_token %}  

        {% for field in form %}
        <div class="form-group row my-3 p-3">
          <label for="{{ field.id_for_label }}">
            {{ field.label }}
            {% if field.field.required %}
              <span class="required text-danger">*</span>
            {% endif %}
          </label>    
          {{ field }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
        {% endfor %}

        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">
            {% if is_edit %}
              Сохранить
            {% else %}
              Добавить
            {% endif %}  
          </button>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
  {% block title %} Пост {{post.text|truncatechars:30 }} {% endblock %}
{% block content %}
{% load thumbnail %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
        <li class="list-group-item">
          Группа: {{ group.title }}
          <a href="{% url 'posts:group_posts' post.group.slug %}">
            Все записи группы
          </a>
      {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: {{ post.author.posts.count }}
      </li>
      <li class="list-group-item">
        <a href= "{% url 'posts:profile' post.author.username %}"> 
          Все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="container py-5">
      <p>{{ post.text }}</p>
    </div>
    {% if post.author == user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
    {% endif %}
    {% include 'posts/includes/comment.html' %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
  {% block title %} Профиль пользователя {{ username }} {% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <div class="mb-5">
    <h1>Все посты пользователя {{ username }}</h1>
    <h3>Всего постов: {{ post_quantity }} </h3>
    {% if not username.username == request.user.username %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' username.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' username.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}"> Подробная информация</a>
        <p>
          {% if post.group %}   
            <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
          {% endif %}
        </p>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}